specs: don't visually test files produced for the digital signature test, they cause errors on ubuntu
They cause this errors

Imagemagick error: Error:    **** Warning: /BBox has zero width or height, which is not allowed.

imageTaken: could not handle image signature_signature_no_certformat-0
Error:    **** Warning: /BBox has zero width or height, which is not allowed.

    at ImageMagick.onerror (/var/lib/jenkins/jobs/node-tepez-pdf-tools/workspace/node_modules/imagemagick-stream/index.js:273:31)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:548:20)
Imagemagick error: Error:
   **** This file had errors that were repaired or ignored.

Imagemagick error: Error:    **** The file was produced by:
   **** >>>> Adobe PDF Library 11.0; modified using iText 2.1.7 by 1T3XT <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.

Maybe it's an imagemagick issue, because on Windows we have a sligtly newer version
which doesn't complain